---
- git:
    repo: ssh://git@vc.shiin.org:2222/devops/thrift-tools.git
    dest: '{{ ansible_user_dir }}/src/thrift-tools'

- file:
    path: '{{ ansible_user_dir }}/src/thrift-tools/tmp'
    state: directory

- template:
    src: ethernet-device-linux.txt
    dest: '{{ ansible_user_dir }}/src/thrift-tools/tmp/ethernet-device.txt'
  when: ansible_system == 'Linux'

- template:
    src: ethernet-device-macos.txt
    dest: '{{ ansible_user_dir }}/src/thrift-tools/tmp/ethernet-device.txt'
  when: ansible_system == 'Darwin'

- template:
    src: domain-linux.txt
    dest: '{{ ansible_user_dir }}/src/thrift-tools/tmp/domain.txt'
  when: ansible_system == 'Linux'

- template:
    src: domain-macos.txt
    dest: '{{ ansible_user_dir }}/src/thrift-tools/tmp/domain.txt'
  when: ansible_system == 'Darwin'
