---
- git:
    repo: ssh://git@vc.shiin.org:2222/devops/thrift-tools.git
    dest: '{{ ansible_user_dir }}/src/thrift-tools'

- file:
    path: '{{ ansible_user_dir }}/src/thrift-tools/tmp'
    state: directory

- template:
    src: ethernet-device.txt
    dest: '{{ ansible_user_dir }}/src/thrift-tools/tmp/ethernet-device.txt'

- template:
    src: domain.txt
    dest: '{{ ansible_user_dir }}/src/thrift-tools/tmp/domain.txt'
